baseURL = 'https://miguoliang.github.io/tomato-clock-cli/'
languageCode = 'en-us'
title = 'Tomato Clock CLI'
theme = 'hugo-book'
googleAnalytics = "G-P7JB73R9VH"

[params]
  bookFavicon = 'favicon.ico'
  bookLogo = 'logo.png'

[markup.goldmark.renderer]
  unsafe = true

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/miguoliang/tomato-clock-cli"
  weight = 10